version: '3.8'

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    environment:
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - GREEN_API_ID=${GREEN_API_ID}
      - GREEN_API_TOKEN=${GREEN_API_TOKEN}
      - GREEN_API_URL=${GREEN_API_URL}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - TELEGRAM_NOTIFICATIONS_ENABLED=true
      - TOKEN_SIGNING_KEY=${TOKEN_SIGNING_KEY}
    networks:
      - app-network
    env_file:
      - .env


networks:
  app-network:
    driver: bridge
